import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Web3Modal } from '../app/context/Web3Modal'
import { Web3Modal } from '../app/context/HelloModel'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body>
        <Web3Modal>{children}</Web3Modal>
      </body>
    </html>
  )
}
